// Date: 28/07/2015 21:08:49
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.leonic.balloons.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBalloon extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape4;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape5;
  
  public ModelBalloon()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 79);
      Shape1.addBox(0F, 2F, 0F, 1, 21, 1);
      Shape1.setRotationPoint(0F, -1F, 0F);
      Shape1.setTextureSize(256, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 38);
      Shape4.addBox(-7F, 0F, -3F, 13, 11, 12);
      Shape4.setRotationPoint(1F, -9F, -2F);
      Shape4.setTextureSize(256, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 80, 35);
      Shape2.addBox(0F, 0F, 0F, 11, 13, 10);
      Shape2.setRotationPoint(-5F, -10F, -4F);
      Shape2.setTextureSize(256, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 80, 0);
      Shape3.addBox(0F, 0F, 0F, 15, 9, 10);
      Shape3.setRotationPoint(-7F, -8F, -4F);
      Shape3.setTextureSize(256, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 11, 9, 14);
      Shape5.setRotationPoint(-5F, -8F, -6F);
      Shape5.setTextureSize(256, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Shape1.render(f5);
    Shape4.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape5.render(f5);
  }
  
  public void renderModel(float f){
	    Shape1.render(f);
	    Shape4.render(f);
	    Shape2.render(f);
	    Shape3.render(f);
	    Shape5.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
}
