// Date: 03/08/2015 11:37:57
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.leonic.balloons.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * Java generated by Techne.
 * Model by ZanyLeonic
 * 
 * @author ZanyLeonic
 * @version 0.1

 */
public class ModelBalloon extends ModelBase
{
  //fields
    ModelRenderer Rope;
    ModelRenderer Balloon1;
    ModelRenderer Balloon2;
    ModelRenderer Balloon3;
    ModelRenderer Balloon4;
  
  public ModelBalloon()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Rope = new ModelRenderer(this, 2, 79);
      Rope.addBox(-1F, 8F, -1F, 2, 14, 2);
      Rope.setRotationPoint(0F, 2F, 0F);
      Rope.setTextureSize(256, 128);
      Rope.mirror = true;
      setRotation(Rope, 0F, 0F, 0F);
      Balloon1 = new ModelRenderer(this, 0, 38);
      Balloon1.addBox(-7F, 7F, -3F, 13, 11, 12);
      Balloon1.setRotationPoint(0.7F, -9F, -3F);
      Balloon1.setTextureSize(256, 128);
      Balloon1.mirror = true;
      setRotation(Balloon1, 0F, 0F, 0F);
      Balloon2 = new ModelRenderer(this, 80, 35);
      Balloon2.addBox(-1F, 7F, 0F, 11, 13, 11);
      Balloon2.setRotationPoint(-4.3F, -10F, -5.266667F);
      Balloon2.setTextureSize(256, 128);
      Balloon2.mirror = true;
      setRotation(Balloon2, 0F, 0F, 0F);
      Balloon3 = new ModelRenderer(this, 80, 0);
      Balloon3.addBox(0F, 7F, 0F, 15, 9, 10);
      Balloon3.setRotationPoint(-7.3F, -8F, -5F);
      Balloon3.setTextureSize(256, 128);
      Balloon3.mirror = true;
      setRotation(Balloon3, 0F, 0F, 0F);
      Balloon4 = new ModelRenderer(this, 0, 0);
      Balloon4.addBox(0F, 7F, -1F, 11, 9, 14);
      Balloon4.setRotationPoint(-5F, -8F, -6F);
      Balloon4.setTextureSize(256, 128);
      Balloon4.mirror = true;
      setRotation(Balloon4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Rope.render(f5);
    Balloon1.render(f5);
    Balloon2.render(f5);
    Balloon3.render(f5);
    Balloon4.render(f5);
  }
    
  public void renderModel(float f){
        Rope.render(f);
        Balloon1.render(f);
        Balloon2.render(f);
        Balloon3.render(f);
        Balloon4.render(f);
  }
 
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
